### PR TITLE
fix(controltower): default to unreserved concurrent executions

### PR DESCRIPTION
**Pull request by jta**

### CODE REVIEW

**Review by aping1 — COMMENTED** [review]
Do we have data here about how may reserved executions we _need_? Saying we need none is kind of a lie.

**Comment by jta** [comment]
Whatever value we pick, we can't guarantee the stack will install successfully. Wouldn't it be better to have a default that always works on install and allow people to tune it to their needs?

**Comment by jta** [comment]
Whatever value we pick, we can't guarantee the stack will install successfully. Wouldn't it be better to have a default that always works on install and allow people to tune it to their needs?

**Review by aping1 — APPROVED** [review]
Started an internal thread about the need for ReservedConcurrent executions, i agree this default will help initial installs so lets do it. Also we will want to backport this to collection.yaml at some point

**Pull request merged**
